apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.deployment.name }}
  labels:
    app: nginx
spec:
  replicas: {{ .values.deployment.replicacount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {docker.io.values.service}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: nginx-conf
          subPath: index.html
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-index-html-configmap

